name = "QuotientCategories"
uuid = "c103c924-3523-4680-a691-c88f3312ec70"
authors = [
	"Kamal Saleh <kamal.saleh@uni-siegen.de>"
]

# Transpiled from GAP's QuotientCategories v2025.08-03
version = "0.0.2"

[deps]
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
ToolsForCategoricalTowers = "e2cf920d-0824-4cbb-97bb-0be40824f89f"
LinearAlgebraForCAP = "3dc4824f-14ac-4ab7-8a60-75dbcd4a9d60"

[weakdeps]

[extensions]

[compat]
julia = "1.11"
CAP = "0.6"
ToolsForCategoricalTowers = "0.0"
LinearAlgebraForCAP = "~0.1.11"
ModulePresentationsForCAP = "~0.1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ModulePresentationsForCAP = "80a941df-def7-4d99-bd07-d3a3a468fbfc"

[targets]
test = ["Test", "Documenter", "ModulePresentationsForCAP"]
