name = "ToolsForCategoricalTowers"
uuid = "e2cf920d-0824-4cbb-97bb-0be40824f89f"
authors = [
	"Mohamed Barakat <mohamed.barakat@uni-siegen.de>"
]

# Transpiled from GAP's ToolsForCategoricalTowers v2026.01-01
version = "0.1.3"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
MonoidalCategories = "bfd98c86-782f-4b94-909f-74167f1eb613"
CartesianCategories = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"

[weakdeps]

[extensions]

[compat]
julia = "1.11"
CAP = "0.6"
MonoidalCategories = "0.2"
CartesianCategories = "0.3"
FinSetsForCAP = "0.2, 0.3"
FreydCategoriesForCAP = "~0.1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Toposes = "36a15fe6-6211-457f-8fdb-aa2e0d2f3052"
FinSetsForCAP = "0a079e9b-4bc2-44fe-a89b-7607e4464786"
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
FreydCategoriesForCAP = "cec356e3-7627-4f73-8308-af32cbf46c2b"

[targets]
test = ["Test", "Documenter", "Toposes", "FinSetsForCAP", "MatricesForHomalg", "FreydCategoriesForCAP"]
